-- Plugin for theming nvim

local theme_colors = require("config.colors")

return {
	"catppuccin/nvim",
	name = "catppuccin",
	lazy = false,
	priority = 1000,
	config = function()
		require("catppuccin").setup({
			float = { transparent = true, solid = true },
			background = {
				light = "latte",
				dark = "mocha",
			},
			color_overrides = {
				frappe = {
					white = theme_colors["color_white"],
					white1 = theme_colors["color_white2"],

					black = theme_colors["color_black"],

					red = theme_colors["color_red"], -- const, return, await, class, private
					rosewater = theme_colors["color_red"],
					flamingo = theme_colors["color_red"],
					maroon = theme_colors["color_red"],
					red1 = theme_colors["color_red1"],

					pink = theme_colors["color_pink"], -- from, import, this @
					mauve = theme_colors["color_pink"], -- from, import, this @

					purple = theme_colors["color_purple1"],

					peach = theme_colors["color_orange"],
					yellow = theme_colors["color_yellow"],

					blue = theme_colors["color_blue"],
					darkblue = theme_colors["color_blue"],
					lavender = theme_colors["color_blue"],

					green = theme_colors["color_green"],

					sapphire = theme_colors["color_sapphire"],
					teal = theme_colors["color_sapphire"],
					sky = theme_colors["color_sapphire"],

					text = theme_colors["color_beige"],

					subtext1 = theme_colors["color_beige1"],
					subtext0 = theme_colors["color_olive"],
					overlay2 = theme_colors["color_beige2"],
					overlay1 = theme_colors["color_brown"],
					overlay0 = theme_colors["color_grey1"],
					surface2 = theme_colors["color_grey2"],
					surface1 = theme_colors["color_grey"],
					surface0 = theme_colors["color_dark_grey"],

					base = theme_colors["color_dark_grey1"],
					mantle = theme_colors["color_dark_grey1"],
					crust = theme_colors["color_dark_grey2"],
				},
			},
			transparent_background = true,
			show_end_of_buffer = false,
			integration_default = false,
			integrations = {
				barbecue = {
					dim_dirname = true,
					bold_basename = true,
					dim_context = false,
					alt_background = false,
				},
				flash = true,
				cmp = true,
				gitsigns = true,
				hop = true,
				illuminate = { enabled = true },
				native_lsp = {
					enabled = true,
					inlay_hints = { background = true },
				},
				neogit = true,
				neotree = true,
				semantic_tokens = true,
				treesitter = true,
				treesitter_context = true,
				vimwiki = true,
				which_key = true,
			},
			highlight_overrides = {
				all = function(colors)
					return {
						Headline1Bg = {
							fg = colors.white1,
							bg = "#82aafa",
							bold = true,
						},
						Headline2Bg = {
							fg = colors.white1,
							bg = "#eed49a",
							bold = true,
						},
						Headline3Bg = {
							fg = colors.white1,
							bg = "#99c79a",
							bold = true,
						},
						Headline4Bg = {
							fg = colors.white1,
							bg = "#e396aa",
							bold = true,
						},
						Headline5Bg = {
							fg = colors.white1,
							bg = "#eb7a7a",
							bold = true,
						},
						Headline6Bg = {
							fg = colors.white1,
							bg = "#e1acfa",
							bold = true,
						},
						FlashCurrent = {
							bold = true,
							fg = colors.red,
						},
						FlashMatch = {
							fg = colors.yellow,
						},
						FlashBackdrop = {
							fg = colors.surface1,
						},
						FlashLabel = {
							bg = colors.red1,
							bold = true,
							fg = colors.white1,
						},
						CmpItemMenu = { fg = colors.surface2 },
						CursorLineNr = { fg = colors.text },
						-- it's possible to make cursorline transparent with kitty only if
						-- it's hardcoded value
						CursorLine = { bg = "#393939" },
						FloatBorder = { bg = "none", fg = colors.subtext1 }, -- colors.surface0 }, difficult to see
						GitSignsChange = { fg = colors.peach },
						LineNr = { fg = colors.surface1 },
						LspInfoBorder = { link = "FloatBorder" },
						NeoTreeDirectoryIcon = { fg = colors.subtext1 },
						NeoTreeDirectoryName = { fg = colors.subtext1 },
						NeoTreeFloatBorder = {
							bg = colors.mantle,
							fg = colors.mantle,
						},
						NeoTreeGitConflict = { fg = colors.red },
						NeoTreeGitDeleted = { fg = colors.red },
						NeoTreeGitIgnored = { fg = colors.surface1 },
						NeoTreeGitModified = { fg = colors.peach },
						NeoTreeGitStaged = { fg = colors.green },
						NeoTreeGitUnstaged = { fg = colors.red },
						NeoTreeGitUntracked = { fg = colors.green },
						NeoTreeIndent = { fg = colors.surface1 },
						NeoTreeNormal = { bg = colors.mantle },
						NeoTreeNormalNC = { bg = colors.mantle },
						NeoTreeRootName = {
							fg = colors.subtext1,
							style = { "bold" },
						},
						NeoTreeTabActive = {
							fg = colors.text,
							bg = colors.mantle,
						},
						NeoTreeTabInactive = {
							fg = colors.surface2,
							bg = colors.crust,
						},
						NeoTreeTabSeparatorActive = {
							fg = colors.mantle,
							bg = colors.mantle,
						},
						NeoTreeTabSeparatorInactive = {
							fg = colors.crust,
							bg = colors.crust,
						},
						NeoTreeWinSeparator = {
							fg = colors.surface1,
							bg = colors.mantle,
						},
						NormalFloat = { bg = "none" },
						Pmenu = { bg = colors.mantle, fg = "" },
						VertSplit = { bg = colors.mantle, fg = colors.surface0 },
						WhichKeyFloat = { bg = colors.mantle },
						YankHighlight = { bg = colors.surface2 },
						FidgetTask = { fg = colors.subtext2 },
						FidgetTitle = { fg = colors.peach },

						IblIndent = { fg = colors.surface0 },
						IblScope = { fg = colors.surface1 },

						Boolean = { fg = colors.pink },
						Number = { fg = colors.pink },
						Float = { fg = colors.pink },

						PreProc = { fg = colors.pink },
						PreCondit = { fg = colors.pink },
						Include = { fg = colors.pink },
						Define = { fg = colors.pink },
						Conditional = { fg = colors.red },
						Repeat = { fg = colors.red },
						Keyword = { fg = colors.red },
						Typedef = { fg = colors.red },
						Exception = { fg = colors.red },
						Statement = { fg = colors.red },

						Error = { fg = colors.red },
						StorageClass = { fg = colors.peach },
						Tag = { fg = colors.peach },
						Label = { fg = colors.peach },
						Structure = { fg = colors.peach },
						Operator = { fg = colors.sapphire },
						Title = { fg = colors.peach },
						Special = { fg = colors.yellow },
						SpecialChar = { fg = colors.yellow },
						Type = { fg = colors.yellow, style = { "bold" } },
						Function = { fg = colors.blue, style = { "bold" } },
						Delimiter = { fg = colors.subtext2 },
						Ignore = { fg = colors.subtext2 },
						Macro = { fg = colors.sapphire },

						TSAnnotation = { fg = colors.pink },
						TSAttribute = { fg = colors.pink },
						TSBoolean = { fg = colors.pink },
						TSCharacter = { fg = colors.sapphire },
						TSCharacterSpecial = { link = "SpecialChar" },
						TSComment = { link = "Comment" },
						TSConditional = { fg = colors.red },
						TSConstBuiltin = { fg = colors.pink },
						TSConstMacro = { fg = colors.pink },
						TSConstant = { fg = colors.text },
						TSConstructor = { fg = colors.green },
						TSDebug = { link = "Debug" },
						TSDefine = { link = "Define" },
						TSEnvironment = { link = "Macro" },
						TSEnvironmentName = { link = "Type" },
						TSError = { link = "Error" },
						TSException = { fg = colors.red },
						TSField = { fg = colors.white },
						TSFloat = { fg = colors.pink },
						TSFuncBuiltin = { fg = colors.green },
						TSFuncMacro = { fg = colors.green },
						TSFunction = { fg = colors.green },
						TSFunctionCall = { fg = colors.green },
						TSInclude = { fg = colors.red },
						TSKeyword = { fg = colors.red },
						TSKeywordFunction = { fg = colors.red },
						TSKeywordOperator = { fg = colors.sapphire },
						TSKeywordReturn = { fg = colors.red },
						TSLabel = { fg = colors.peach },
						TSLiteral = { link = "String" },
						TSMath = { fg = colors.blue },
						TSMethod = { fg = colors.green },
						TSMethodCall = { fg = colors.green },
						TSNamespace = { fg = colors.yellow },
						TSNone = { fg = colors.text },
						TSNumber = { fg = colors.pink },
						-- TSOperator = { fg = colors.sapphire },
						TSOperator = { fg = colors.peach },
						TSParameter = { fg = colors.text },
						TSParameterReference = { fg = colors.text },
						TSPreProc = { link = "PreProc" },
						TSProperty = { fg = colors.white },
						TSPunctBracket = { fg = colors.text },
						TSPunctDelimiter = { link = "Delimiter" },
						TSPunctSpecial = { fg = colors.blue },
						TSRepeat = { fg = colors.red },
						TSStorageClass = { fg = colors.peach },
						TSStorageClassLifetime = { fg = colors.peach },
						TSStrike = { fg = colors.subtext2 },
						TSString = { fg = colors.sapphire },
						TSStringEscape = { fg = colors.green },
						TSStringRegex = { fg = colors.green },
						TSStringSpecial = { link = "SpecialChar" },
						TSSymbol = { fg = colors.text },
						TSTag = { fg = colors.peach },
						TSTagAttribute = { fg = colors.green },
						TSTagDelimiter = { fg = colors.green },
						TSText = { fg = colors.green },
						TSTextReference = { link = "Constant" },
						TSTitle = { link = "Title" },
						TSTodo = { link = "Todo" },
						TSType = { fg = colors.yellow, style = { "bold" } },
						TSTypeBuiltin = {
							fg = colors.yellow,
							style = { "bold" },
						},
						TSTypeDefinition = {
							fg = colors.yellow,
							style = { "bold" },
						},
						TSTypeQualifier = {
							fg = colors.peach,
							style = { "bold" },
						},
						TSURI = { fg = colors.blue },
						-- TSVariable = { fg = colors.white },
						TSVariable = { fg = colors.text },
						TSVariableBuiltin = { fg = colors.pink },

						["@annotation"] = { link = "TSAnnotation" },
						["@attribute"] = { link = "TSAttribute" },
						["@boolean"] = { link = "TSBoolean" },
						["@character"] = { link = "TSCharacter" },
						["@character.special"] = { link = "TSCharacterSpecial" },
						["@comment"] = { link = "TSComment" },
						["@conceal"] = { link = "Grey" },
						["@conditional"] = { link = "TSConditional" },
						["@constant"] = { link = "TSConstant" },
						["@constant.builtin"] = { link = "TSConstBuiltin" },
						["@constant.macro"] = { link = "TSConstMacro" },
						["@constructor"] = { link = "TSConstructor" },
						["@debug"] = { link = "TSDebug" },
						["@define"] = { link = "TSDefine" },
						["@error"] = { link = "TSError" },
						["@exception"] = { link = "TSException" },
						["@field"] = { link = "TSField" },
						["@float"] = { link = "TSFloat" },
						["@function"] = { link = "TSFunction" },
						["@function.builtin"] = { link = "TSFuncBuiltin" },
						["@function.call"] = { link = "TSFunctionCall" },
						["@function.macro"] = { link = "TSFuncMacro" },
						["@include"] = { link = "TSInclude" },
						["@keyword"] = { link = "TSKeyword" },
						["@keyword.function"] = { link = "TSKeywordFunction" },
						["@keyword.operator"] = { link = "TSKeywordOperator" },
						["@keyword.return"] = { link = "TSKeywordReturn" },
						["@label"] = { link = "TSLabel" },
						["@math"] = { link = "TSMath" },
						["@method"] = { link = "TSMethod" },
						["@method.call"] = { link = "TSMethodCall" },
						["@namespace"] = { link = "TSNamespace" },
						["@none"] = { link = "TSNone" },
						["@number"] = { link = "TSNumber" },
						["@operator"] = { link = "TSOperator" },
						["@parameter"] = { link = "TSParameter" },
						["@parameter.reference"] = {
							link = "TSParameterReference",
						},
						["@preproc"] = { link = "TSPreProc" },
						["@property"] = { link = "TSProperty" },
						["@punctuation.bracket"] = { link = "TSPunctBracket" },
						["@punctuation.delimiter"] = {
							link = "TSPunctDelimiter",
						},
						["@punctuation.special"] = { link = "TSPunctSpecial" },
						["@repeat"] = { link = "TSRepeat" },
						["@storageclass"] = { link = "TSStorageClass" },
						["@storageclass.lifetime"] = {
							link = "TSStorageClassLifetime",
						},
						["@strike"] = { link = "TSStrike" },
						["@string"] = { link = "TSString" },
						["@string.escape"] = { link = "TSStringEscape" },
						["@string.regex"] = { link = "TSStringRegex" },
						["@string.special"] = { link = "TSStringSpecial" },
						["@symbol"] = { link = "TSSymbol" },
						["@tag"] = { link = "TSTag" },
						["@tag.attribute"] = { link = "TSTagAttribute" },
						["@tag.delimiter"] = { link = "TSTagDelimiter" },
						["@text"] = { link = "TSText" },
						["@text.danger"] = { link = "TSDanger" },
						["@text.diff.add"] = { link = "diffAdded" },
						["@text.diff.delete"] = { link = "diffRemoved" },
						["@text.emphasis"] = { link = "TSEmphasis" },
						["@text.environment"] = { link = "TSEnvironment" },
						["@text.environment.name"] = {
							link = "TSEnvironmentName",
						},
						["@text.literal"] = { link = "TSLiteral" },
						["@text.math"] = { link = "TSMath" },
						["@text.note"] = { link = "TSNote" },
						["@text.reference"] = { link = "TSTextReference" },
						["@text.strike"] = { link = "TSStrike" },
						["@text.strong"] = { link = "TSStrong" },
						["@text.title"] = { link = "TSTitle" },
						["@text.todo"] = { link = "TSTodo" },
						["@text.todo.checked"] = { link = "Green" },
						["@text.todo.unchecked"] = { link = "Ignore" },
						["@text.underline"] = { link = "TSUnderline" },
						["@text.uri"] = { link = "TSURI" },
						["@text.warning"] = { link = "TSWarning" },
						["@todo"] = { link = "TSTodo" },
						-- ["@type"] = { fg = colors.white },
						["@type"] = { fg = colors.text },
						["@type.builtin"] = { link = "TSTypeBuiltin" },
						["@type.definition"] = { link = "TSTypeDefinition" },
						["@type.qualifier"] = { link = "TSTypeQualifier" },
						["@uri"] = { link = "TSURI" },
						["@variable"] = { link = "TSVariable" },
						["@variable.builtin"] = { link = "TSVariableBuiltin" },

						["@lsp.type.class"] = { link = "TSType" },
						["@lsp.type.comment"] = { link = "TSComment" },
						["@lsp.type.decorator"] = { link = "TSFunction" },
						["@lsp.type.enum"] = { link = "TSType" },
						["@lsp.type.enumMember"] = { link = "TSProperty" },
						["@lsp.type.events"] = { link = "TSLabel" },
						["@lsp.type.function"] = { link = "TSFunction" },
						["@lsp.type.interface"] = { link = "TSType" },
						["@lsp.type.keyword"] = { link = "TSKeyword" },
						["@lsp.type.macro"] = { link = "TSConstMacro" },
						["@lsp.type.method"] = { link = "TSMethod" },
						["@lsp.type.modifier"] = { link = "TSTypeQualifier" },
						["@lsp.type.namespace"] = { link = "TSNamespace" },
						["@lsp.type.number"] = { link = "TSNumber" },
						["@lsp.type.operator"] = { link = "TSOperator" },
						["@lsp.type.parameter"] = { link = "TSParameter" },
						["@lsp.type.property"] = { link = "TSProperty" },
						["@lsp.type.regexp"] = { link = "TSStringRegex" },
						["@lsp.type.string"] = { link = "TSString" },
						["@lsp.type.struct"] = { link = "TSType" },
						["@lsp.type.type"] = { link = "TSType" },
						["@lsp.type.typeParameter"] = {
							link = "TSTypeDefinition",
						},
						["@lsp.type.variable"] = { link = "TSVariable" },
					}
				end,
			},
		})

		vim.api.nvim_command("colorscheme catppuccin-frappe")
	end,
}
